name: Validar Landing Page

on:
  push:
  pull_request:

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Verificar index.html
        run: test -f index.html

      - name: Verificar style.css
        run: test -f style.css

      - name: Verificar script.js
        run: test -f script.js

      - name: Verificar README.md
        run: test -f README.md